### ISSUE TITLE
Can't get it work in no blocking mode

### ISSUE THREAD

**Issue by mehdirayan** [s-h-a-d-o-w/node-native-dialog#4]
I 'm using the two dialog boxs ( show and showSync,), but the two  boxs behaves in the same way ( blocking mode).
I'm in windows 10, node@18.13.0
Is it related to the new version of winax?

**Comment by s-h-a-d-o-w** [comment]
Did it work with the previous major version?

Because taking a quick look at my years old code here, I suspect it's simply down to the very naive "async" implementation, which actually isn't async. And so I'm guessing it never actually worked.
Also, it looks like winax only offers sync operation and so it's going to block execution, no way around it.

**Comment by s-h-a-d-o-w** [comment]
After looking at bit into this, I realized that this library isn't really necessary and so I'm archiving it. (See note in README)
